driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-6.7
- name: centos-7.1
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list:
    - "recipe[ohai]"
    - "recipe[ohai_test::add_hint_immediate]"
    - "recipe[ohai_test::node_dump]"
